import { SearchRequest } from '../api/search/search/search-request';
export declare function buildMockSearchRequest(config?: Partial<SearchRequest>): {
    url: string;
    accessToken: string;
    organizationId: string;
    q?: string | undefined;
    aq?: string | undefined;
    cq?: string | undefined;
    lq?: string | undefined;
    dq?: string | undefined;
    numberOfResults?: number | undefined;
    firstResult?: number | undefined;
    sortCriteria?: string | undefined;
    facets?: import("../features/facets/generic/interfaces/generic-facet-request").AnyFacetRequest[] | undefined;
    context?: Record<string, string | string[]> | undefined;
    dictionaryFieldContext?: Record<string, string> | undefined;
    enableDidYouMean?: boolean | undefined;
    enableQuerySyntax?: boolean | undefined;
    fieldsToInclude?: string[] | undefined;
    pipeline?: string | undefined;
    searchHub?: string | undefined;
    facetOptions?: import("../features/facet-options/facet-options").FacetOptions | undefined;
    visitorId?: string | undefined;
    debug?: boolean | undefined;
    locale?: string | undefined;
    filterField?: string | undefined;
    parentField?: string | undefined;
    childField?: string | undefined;
    filterFieldRange?: number | undefined;
    tab: string;
    referrer: string;
    timezone: string;
    analytics?: {
        clientId: string;
        deviceId?: string | undefined;
        pageId: string;
        clientTimestamp: string;
        documentReferrer: string;
        originContext: string;
        userDisplayName: string;
    } | undefined;
    excerptLength?: number | undefined;
    actionsHistory?: import("coveo.analytics/dist/definitions/history").HistoryElement[] | undefined;
};
